/**
 * Per-page SEO hook — keeps page meta in sync with route navigation.
 *
 * Updates on every render of a page that calls it:
 *   • <title>
 *   • <meta name="description">
 *   • Open Graph (og:title / og:description / og:url / og:image)
 *   • Twitter Card (twitter:title / twitter:description / twitter:image)
 *   • <link rel="canonical">
 *   • Optional JSON-LD <script> blocks (cleaned up on unmount)
 *
 * Site-wide Organization / MedicalBusiness JSON-LD lives in index.html
 * so it survives even before the SPA hydrates.
 */
import { useEffect } from 'react'

/** Canonical site URL — used for og:url, canonical, and JSON-LD @ids. */
export const SITE_URL = 'https://thelongevitycentre.com'

/**
 * Default OG/Twitter image for pages that don't supply their own.
 * 1200×630 JPEG composited from a brand mood photo + page tagline.
 * Generated by docs/build_og.py — do not edit the JPEG by hand; rerun
 * the script if the brand image or tagline changes.
 */
const DEFAULT_OG_IMAGE = '/og/default.jpg'

export type JsonLd = Record<string, unknown>

export interface PageMeta {
  /** Page title — keep ≤ 60 chars for full display in SERPs. */
  title: string
  /** Description — keep 140-160 chars to avoid SERP truncation. */
  description: string
  /** Path including leading slash, e.g. '/about'. Defaults to '/'. */
  path?: string
  /** Path or absolute URL of the OG image. Defaults to the brand logo. */
  ogImage?: string
  /** One or more JSON-LD objects to inject into <head>. */
  jsonLd?: JsonLd | JsonLd[]
}

function setNamedMeta(name: string, content: string): void {
  let el = document.head.querySelector<HTMLMetaElement>(`meta[name="${name}"]`)
  if (!el) {
    el = document.createElement('meta')
    el.setAttribute('name', name)
    document.head.appendChild(el)
  }
  el.content = content
}

function setPropMeta(prop: string, content: string): void {
  let el = document.head.querySelector<HTMLMetaElement>(`meta[property="${prop}"]`)
  if (!el) {
    el = document.createElement('meta')
    el.setAttribute('property', prop)
    document.head.appendChild(el)
  }
  el.content = content
}

function setCanonical(url: string): void {
  let el = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]')
  if (!el) {
    el = document.createElement('link')
    el.rel = 'canonical'
    document.head.appendChild(el)
  }
  el.href = url
}

/**
 * Build a BreadcrumbList JSON-LD object for detail pages.
 *
 * @example
 *   breadcrumbList([
 *     { name: 'Home',         url: '/' },
 *     { name: 'Diagnostics',  url: '/diagnostics' },
 *     { name: 'Oligoscan',    url: '/diagnostics/oligoscan' },
 *   ])
 */
export function breadcrumbList(
  items: { name: string; url: string }[]
): JsonLd {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: item.url.startsWith('http') ? item.url : SITE_URL + item.url,
    })),
  }
}

/**
 * Set per-route head metadata (title, description, OG, Twitter, canonical,
 * optional JSON-LD blocks). Call once per page from a top-level component.
 */
export function useDocumentMeta(meta: PageMeta): void {
  useEffect(() => {
    const path = meta.path ?? '/'
    const url = SITE_URL + path
    const ogImage = meta.ogImage
      ? meta.ogImage.startsWith('http')
        ? meta.ogImage
        : SITE_URL + meta.ogImage
      : SITE_URL + DEFAULT_OG_IMAGE

    document.title = meta.title
    setNamedMeta('description', meta.description)
    setPropMeta('og:title', meta.title)
    setPropMeta('og:description', meta.description)
    setPropMeta('og:url', url)
    setPropMeta('og:image', ogImage)
    setNamedMeta('twitter:title', meta.title)
    setNamedMeta('twitter:description', meta.description)
    setNamedMeta('twitter:image', ogImage)
    setCanonical(url)

    // Inject per-page JSON-LD blocks. Tagged with data-page-jsonld so we
    // only remove what we injected — never the static blocks in index.html.
    const injected: HTMLScriptElement[] = []
    if (meta.jsonLd) {
      const items = Array.isArray(meta.jsonLd) ? meta.jsonLd : [meta.jsonLd]
      items.forEach((item) => {
        const script = document.createElement('script')
        script.type = 'application/ld+json'
        script.dataset.pageJsonld = '1'
        script.textContent = JSON.stringify(item)
        document.head.appendChild(script)
        injected.push(script)
      })
    }

    return () => {
      injected.forEach((s) => s.remove())
    }
  }, [meta])
}
